### ISSUE TITLE
找不到文件是怎么回事呀

### ISSUE THREAD

**Issue by duyihun** [Yiyiyimu/QQ_History_Backup#16]
找不到文件是怎么回事呀
日志：
OSError('File not found. Please report your directory layout.')Traceback (most recent call last):
  File "QQ_History.py", line 279, in main
  File "QQ_History.py", line 36, in __init__
  File "QQ_History.py", line 206, in get_key
  File "QQ_History.py", line 221, in unify_path
OSError: File not found. Please report your directory layout.

**Comment by duyihun** [comment]
![image](https://user-images.githubusercontent.com/83807357/117413826-036ed280-af49-11eb-955e-b9647744d929.png)

**Comment by Yiyiyimu** [comment]
可以找到`com.tencent.mobileqq/f/kc`这个文件吗，如果没有的话，可以试一下1.41

**Comment by duyihun** [comment]
我还发现有聊天记录时间顺序错乱的问题。

**Comment by duyihun** [comment]
![image](https://user-images.githubusercontent.com/83807357/117981529-ac616700-b367-11eb-8a4e-e520a0c22940.png)
注意看右下角的滑条，四月的里面加了一些别的月份的。

**Comment by duyihun** [comment]
![image](https://user-images.githubusercontent.com/83807357/117981929-12e68500-b368-11eb-9683-3fff69620e7d.png)
哈哈。甚至一天之内的也会乱。

**Comment by duyihun** [comment]
![image](https://user-images.githubusercontent.com/83807357/117982219-6062f200-b368-11eb-90f5-7d4dec98ab0f.png)
这个看的比较明白。

**Comment by duyihun** [comment]
解码失败的图也没什么特点。

> > 我发现合并图片的选项是反的。不合并反而合并了
> 
> 感谢提醒！
> 
> > 还有一个问题是，图片变成【图片】是为什么呢？
> > 我还发现有聊天记录时间顺序错乱的问题。
> 
> 变成`[图片]`是解码这张图片的时候失败了造成的，那张图片和其他的有什么不一样吗，或者是有之前没有点开过之类的吗
> 
> 时间错乱的问题我这边没有碰到过，那段记录有什么和其他的不一样的情况吗，方便的话可以截个打码的图吗

**Comment by duyihun** [comment]
![image](https://user-images.githubusercontent.com/83807357/117985455-4bd42900-b36b-11eb-81a5-280db8a48a4a.png)
我问题好多啊，哈哈。“[emoji:255]#”这个是emoji表情没加载出来吗？

**Comment by Yiyiyimu** [comment]
嗯的确之前没有收到过这个问题的反馈。我这边有两个方法：
1. 用 sqlite studio 打开 `databases/#QQ名#.db`，用`files/kc`里的密钥做解密，看里面的聊天记录的这一段时间顺序对不对。如果本身就不对的话我这边就没什么办法了，碰到了的话可以手动调整下html里的顺序。
2. 如果还是不行的话，如果相信我的话可以考虑把文件发给我，我再试试debug

emoji的问题可以看下聊天记录里面本身是什么表情，再对应看看emoticon这个文件夹里有没有这个表情

**Comment by duyihun** [comment]
我用别的软件导出来里面的时间是对的。所以文件本身应该没问题。你要db还是HTML呀。

**Comment by Yiyiyimu** [comment]
噢好，整个`com.tencent.mobileqq`文件吧。要是太大的话db和kc应该就够。如果要看图片的话把`chatimg`也发一下

**Comment by duyihun** [comment]
> 噢好，整个`com.tencent.mobileqq`文件吧。要是太大的话db和kc应该就够。如果要看图片的话把`chatimg`也发一下

发你邮箱了

**Comment by Yiyiyimu** [comment]
图片顺序问题修好了，感谢报告问题！！

emoji 我没有在那个文件里看到 `[emoji:255]`，可以发一下本身聊天记录里面这个 emoji 长什么样吗

**Comment by duyihun** [comment]
![image](https://user-images.githubusercontent.com/83807357/118352530-8371e980-b594-11eb-8407-6c496f62f10d.png)
我发现这是一个QQ的一个表情包里的。叫"嗷大喵小表情"。

> 图片顺序问题修好了，感谢报告问题！！
> 
> emoji 我没有在那个文件里看到 `[emoji:255]`，可以发一下本身聊天记录里面这个 emoji 长什么样吗

**Comment by duyihun** [comment]
> ![image](https://user-images.githubusercontent.com/83807357/118352530-8371e980-b594-11eb-8407-6c496f62f10d.png)
> 我发现这是一个QQ的一个表情包里的。叫"嗷大喵小表情"。
> 
> > 图片顺序问题修好了，感谢报告问题！！
> > emoji 我没有在那个文件里看到 `[emoji:255]`，可以发一下本身聊天记录里面这个 emoji 长什么样吗

/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/.emotionsm/11/
表情包的路径
[11.zip](https://github.com/Yiyiyimu/QQ_History_Backup/files/6484696/11.zip)

**Comment by Yiyiyimu** [comment]
表情包应该就不会支持了,看了下没有搞懂有什么解析的规律 🤣
