### ISSUE TITLE
支持群消息导出

### ISSUE THREAD

**Issue by Yiyiyimu** [Yiyiyimu/QQ_History_Backup#4]
UI加个二选一的选项

**Comment by ous50** [comment]
没有看到群消息的选项啊？

**Comment by Yiyiyimu** [comment]
@ous50 现在支持了，可以试一下

**Comment by ous50** [comment]
> @ous50 现在支持了，可以试一下

好了，现在能看了

**Comment by Yiyiyimu** [comment]
@ous50 现在支持群消息ID填充成备注/昵称了，可以再试试

**Comment by ous50** [comment]
> @ous50 现在支持群消息ID填充成备注/昵称了，可以再试试

好强！

**Comment by ous50** [comment]
实测把整个文件夹复制出来还是太慢了（
建议说明只需复制database和files

**Comment by Yiyiyimu** [comment]
@ous50 多谢提醒。如果没有root是通过备份的途径的话，是直接导出一整个压缩文件的，就没有考虑到这个问题。我去加上一句
