### ISSUE TITLE
# 在使用本exe导出聊天记录后全是乱码，请问怎末解决，其中log没有报错

### ISSUE THREAD

**Issue by hxycom** [Yiyiyimu/QQ_History_Backup#5]
> 
![image](https://user-images.githubusercontent.com/43508398/95164370-701bc600-07dc-11eb-87f5-b8154209346a.png)

**Comment by Yiyiyimu** [comment]
我这边没有碰到这个问题，如果方便的话发下聊天记录到邮箱，我看能不能复现

**Comment by spider-ready** [comment]
> 我这边没有碰到这个问题，如果方便的话发下聊天记录到邮箱，我看能不能复现

麻烦你了，暂时不需要了，谢谢。

**Comment by hxycom** [comment]
> 我这边没有碰到这个问题，如果方便的话发下聊天记录到邮箱，我看能不能复现。

麻烦你了，暂时不需要了，谢谢你！
